//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloMD_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Orden_Completa
    {
        public int Orden_Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Id_Persona { get; set; }
        public string Nombre_Completo { get; set; }
        public string Persona_Tipo_descripcion { get; set; }
        public int Id_Tipo { get; set; }
        public string Tipo_de_orden_descripcion { get; set; }
        public byte Id_Condiciones { get; set; }
        public string Condiciones_Descripcion { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal Recargo { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> Id_Estatus { get; set; }
        public string Estatus_Descripcion { get; set; }
        public string SecuenciaEditable { get; set; }
        public string IdEditable { get; set; }
        public string Secuencia_Gobierno { get; set; }
        public string Comentario { get; set; }
        public int Id_Producto { get; set; }
        public string Detalles_Descripcion { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Impuesto { get; set; }
        public decimal Monto { get; set; }
    }
}
