//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloMD_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Producto
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public decimal Cantidad { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public decimal Costo { get; set; }
        public byte Id_Impuesto { get; set; }
        public string Descripcion_Impuesto { get; set; }
        public string Leyenda { get; set; }
        public decimal Tasa { get; set; }
        public byte Id_Tipo { get; set; }
        public string Tipo_Descripcion { get; set; }
        public int Id_Estatus { get; set; }
        public string Estatus_Descripcion { get; set; }
    }
}
